version: "3"
services:
  inventory-api:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    env_file: 
      - ./.env
    command: npm run dev
    